### PR TITLE
Fix upstream repository detection.

### LINKED ISSUE #111: fatal: bad sha1 reference /master
If this 
UPSTREAM_REMOTE=$(git remote -v | grep fetch | grep 'timvideos/HDMI2USB-litex-firmware
should be the name of this repo: litex-buildenv
then that's the problem and you can stop reading.

otherwise, her is what happens:

 trying to do:  https://github.com/timvideos/litex-buildenv/wiki/HowTo-FuPy-on-a-Digilent-Arty-A7  

```
git clone https://github.com/timvideos/litex-buildenv.git
cd litex-buildenv/
# Download the prebuilt gateware file
./scripts/download-prebuilt.sh
```
https://github.com/timvideos/litex-buildenv/blob/master/scripts/download-prebuilt.sh#L44
```
UPSTREAM_REMOTE=$(git remote -v | grep fetch | grep 'timvideos/HDMI2USB-litex-firmware' | sed -e's/\t.*$//')
```
```
(LX P=arty T=base F=micropython) juser@gator:~/tv/litex-buildenv$ git remote -v | grep fetch
origin	https://github.com/timvideos/litex-buildenv.git (fetch)
```
litex-buildenv <> HDMI2USB-litex-firmware so UPSTREAM_REMOTE is blank.

https://github.com/timvideos/litex-buildenv/blob/master/scripts/download-prebuilt.sh#L46
```
UPSTREAM_GITREV=$(git show-branch --merge-base $UPSTREAM_REMOTE/$UPSTREAM_BRANCH HEAD)
```
```
(LX P=arty T=base F=micropython) juser@gator:~/tv/litex-buildenv$ ./scripts/download-prebuilt.sh
+ GITHUB_URL=https://github.com/timvideos/HDMI2USB-firmware-prebuilt/
+ UPSTREAM_BRANCH=master
++ git remote -v
++ grep fetch
++ grep timvideos/HDMI2USB-litex-firmware
++ sed '-es/\t.*$//'
+ UPSTREAM_REMOTE=
++ git show-branch --merge-base /master HEAD
fatal: bad sha1 reference /master
```
plugging in what I think is expected:
```
UPSTREAM_REMOTE=origin
 git show-branch --merge-base origin/master HEAD
4383c27278e0ba6e56520a327982beb1c72527aa
```

### PR DESCRIPTION
**Pull request by CarlFK**
Fixes #111.

### CODE REVIEW

File: scripts/download-prebuilt.sh [hunk 1]
```diff
@@ -41,7 +41,7 @@ set -e
 GITHUB_URL=https://github.com/timvideos/HDMI2USB-firmware-prebuilt/
 
 UPSTREAM_BRANCH=master
-UPSTREAM_REMOTE=$(git remote -v | grep fetch | grep 'timvideos/HDMI2USB-litex-firmware' | sed -e's/\t.*$//')
+UPSTREAM_REMOTE=$(git remote -v | grep fetch | grep 'timvideos/litex-buildenv' | sed -e's/\t.*$//')
```
Comment (mithro) [inline scripts/download-prebuilt.sh]: Could you change this to an or? I think it would be;
`grep 'timvideos/litex-buildenv|timvideos/HDMI2USB-litex-firmware'`

Comment (CarlFK) [reply scripts/download-prebuilt.sh]: Is the name of the repo important vs "find the timvideos" one?

does putting "fetch" in its own grep make it easier to read?  makes me edgy :p

have some options.  

$ git remote -v | 
grep -E 'timvideos/(litex-buildenv|HDMI2USB-litex-firmware) \(fetch\)' 
origin	https://github.com/timvideos/HDMI2USB-litex-firmware (fetch)

grep '\(fetch\)' |  grep -E 'timvideos/(litex-buildenv|HDMI2USB-litex-firmware)' 
origin	https://github.com/timvideos/HDMI2USB-litex-firmware (fetch)

grep 'timvideos/.*\(fetch\)' 
origin	https://github.com/timvideos/HDMI2USB-litex-firmware (fetch)

**Comment by mithro** [comment]
I rebased this onto master. Will merge if it goes green.

File: scripts/download-prebuilt.sh (hunk 1 above)
Comment (mithro) [reply scripts/download-prebuilt.sh]: I went with `grep '(fetch)' | grep -E 'timvideos/(litex-buildenv|HDMI2USB-litex-firmware)'`
